name: 🐞 Reporte de bug
description: Reporta un error o comportamiento inesperado.
title: "[BUG] <Descripción corta>"
labels: ["bug"]
body:
  - type: textarea
    id: descripcion
    attributes:
      label: Descripción del problema
      description: Explica qué está pasando y qué esperabas que pasara.
      placeholder: "El botón 'Guardar' no funciona al hacer clic."
    validations:
      required: true

  - type: textarea
    id: pasos
    attributes:
      label: Pasos para reproducir
      description: Indica cómo se puede reproducir el error.
      placeholder: |
        1. Ir a la página de perfil
        2. Cambiar el idioma
        3. Hacer clic en 'Guardar'
        4. Ver el error

  - type: input
    id: entorno
    attributes:
      label: Entorno
      placeholder: "Ejemplo: Windows 11 / Chrome 128 / Node.js 20"

  - type: textarea
    id: evidencias
    attributes:
      label: Evidencias (capturas, logs, etc.)
      description: Adjunta imágenes o fragmentos de código relevantes.
